params:
  seed: 42
  algo: { name: "ppo" }
  model: { name: "continuous_a2c" }
  network:
    name: actor_critic
    mlp:
      units: [256, 256]
      activation: elu
  config:
    horizon_length: 32
    minibatch_size: 16384
    mini_epochs: 4
    num_actors: 64
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    grad_norm: 1.0
    clip_param: 0.2
    entropy_coef: 0.0
    value_loss_coef: 2.0
    max_epochs: 1000
    save_best_after: 50
    save_frequency: 50
    normalize_input: true
    normalize_value: true
    clip_value: true